name: Keep Render App Awake

on:
  schedule:
    - cron: "*/10 * * * *"  # Runs every 10 minutes UTC

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping your Render app
        run: curl --silent https://tubesnap-vko7.onrender.com > /dev/null
